import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const elements=new Map();
const element=()=>({hidden:false,style:{},classList:{add(){},remove(){}},setAttribute(){},append(){},addEventListener(type,fn){this[type]=fn;}});
const drawing=new Proxy({createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{})});
const document={hidden:false,querySelector(s){if(!elements.has(s))elements.set(s,element());return elements.get(s);},createElement:element,addEventListener(type,fn){this[type]=fn;}};
document.querySelector('#sky').getContext=()=>drawing;
const context=vm.createContext({document,window:{addEventListener(){}},innerWidth:844,innerHeight:390,devicePixelRatio:2,Image:class{},requestAnimationFrame:()=>1,cancelAnimationFrame(){},console,assert});
vm.runInContext(readFileSync(new URL('../game.js',import.meta.url),'utf8')+`
const step=seconds=>{for(let i=0;i<Math.ceil(seconds/.016);i++)update(.016);};
started=true;rockets=[];particles=[];glows=[];
for(let i=0;i<14;i++){touch(150+i*25,110);step(.85);}
assert.equal(count,14);assert.equal(finale,null);
touch(410,100);step(.85);assert.ok(finale);step(5.2);assert.equal(finale,null);assert.equal(count,0);
for(let i=0;i<15;i++){touch(200+i*20,110);step(.85);}assert.ok(finale);step(5.2);assert.equal(count,0);
for(let i=0;i<1000;i++)touch(300,100);assert.ok(rockets.length<=10);assert.ok(rings.length<=36);assert.ok(particles.length<=1500);
step(4);assert.equal(rockets.length,0);
for(const type of ['round','ring','willow','star','heart','smile']){explode({tx:2,ty:2,type,color:'#ffd886',auto:true});}draw();assert.ok(particles.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.vx)));
const before=count;touch(400,380);assert.equal(count,before);
document.hidden=true;activity();assert.equal(raf,0);document.hidden=false;activity();assert.equal(raf,1);
innerWidth=390;innerHeight=844;resize();activity();assert.equal(raf,0);const n=rockets.length;touch(100,100);assert.equal(rockets.length,n);
innerWidth=844;innerHeight=390;resize();activity();assert.equal(raf,1);assert.equal(particles.length,0);
beginGesture(1,100,100);moveGesture(1,300,150);endGesture(1);assert.ok(swipeBlooms.length>=4);step(2);assert.equal(swipeBlooms.length,0);assert.ok(particles.length>0);
beginGesture(2,100,100);moveGesture(2,110,100);endGesture(2);assert.equal(swipeBlooms.length,0);
beginGesture(3,100,100);moveGesture(3,300,100);endGesture(3,true);assert.equal(swipeBlooms.length,0);
for(let i=0;i<20;i++){beginGesture(i,100,100);moveGesture(i,600,100);endGesture(i);}assert.ok(swipeBlooms.length<=48);
beginGesture(9,100,100);document.hidden=true;activity();assert.equal(gestures.size,0);assert.equal(swipeBlooms.length,0);
document.hidden=false;activity();finale=null;rockets=[];particles=[];nextStarAt=clock+2;
step(1);assert.equal(luckyStars.filter(Boolean).length,0);step(1.1);assert.equal(luckyStars.filter(Boolean).length,1);
step(4);assert.equal(luckyStars.filter(Boolean).length,2);step(4);assert.equal(luckyStars.filter(Boolean).length,3);
const waiting=[...luckyStars];step(120);assert.deepEqual(luckyStars,waiting);assert.equal(starRewards,0);
for(let i=0;i<3;i++)for(let j=i+1;j<3;j++)assert.ok(Math.hypot((luckyStars[i].x-luckyStars[j].x)*480,(luckyStars[i].y-luckyStars[j].y)*320)>116);
const sx=luckyStars[0].x*width,sy=luckyStars[0].y*height;
touch(10,10);assert.equal(luckyStars[0].claimedAt,null);assert.ok(rockets.length>0);
const launches=rockets.length;beginGesture(51,sx+50,sy);assert.equal(gestures.has(51),false);assert.equal(rockets.length,launches);
claimStar(sx,sy);step(.6);assert.equal(starRewards,1);assert.equal(luckyStars[0],null);assert.ok(particles.length>0);
assert.equal(luckyStars[1],waiting[1]);assert.equal(luckyStars[2],waiting[2]);step(2.1);assert.ok(luckyStars[0]);
const next=[...luckyStars];document.hidden=true;activity();assert.deepEqual(luckyStars,next);
innerWidth=390;innerHeight=844;resize();assert.deepEqual(luckyStars,next);innerWidth=844;innerHeight=390;resize();
document.hidden=false;activity();for(const star of luckyStars)touch(star.x*width,star.y*height);step(.6);assert.equal(starRewards,4);
step(15);assert.equal(luckyStars.filter(Boolean).length,3);
console.log('PASS: persistent star, generous hit area, single reward, respawn and rotation; swipe, cancellation, multitouch bounds, repeated finales, rapid-input bounds, edge shapes, audience input, visibility and rotation');
`,context);
